package com.rxee.dataservice.mapper;

import com.rxee.entity.ProductInfo;
import org.apache.ibatis.annotations.*;

public interface ProductInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_product_info
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    @Delete({
        "delete from b_product_info",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_product_info
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    @Insert({
        "insert into b_product_info (id, product_name, ",
        "rate, cycle, release_time, ",
        "product_type, product_no, ",
        "product_money, left_product_money, ",
        "bid_min_limit, bid_max_limit, ",
        "product_status, product_full_time, ",
        "product_desc)",
        "values (#{id,jdbcType=INTEGER}, #{productName,jdbcType=VARCHAR}, ",
        "#{rate,jdbcType=DECIMAL}, #{cycle,jdbcType=INTEGER}, #{releaseTime,jdbcType=DATE}, ",
        "#{productType,jdbcType=INTEGER}, #{productNo,jdbcType=VARCHAR}, ",
        "#{productMoney,jdbcType=DECIMAL}, #{leftProductMoney,jdbcType=DECIMAL}, ",
        "#{bidMinLimit,jdbcType=DECIMAL}, #{bidMaxLimit,jdbcType=DECIMAL}, ",
        "#{productStatus,jdbcType=INTEGER}, #{productFullTime,jdbcType=TIMESTAMP}, ",
        "#{productDesc,jdbcType=VARCHAR})"
    })
    int insert(ProductInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_product_info
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    int insertSelective(ProductInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_product_info
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    @Select({
        "select",
        "id, product_name, rate, cycle, release_time, product_type, product_no, product_money, ",
        "left_product_money, bid_min_limit, bid_max_limit, product_status, product_full_time, ",
        "product_desc",
        "from b_product_info",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.rxee.backend.mapper.ProductInfoMapper.BaseResultMap")
    ProductInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_product_info
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    int updateByPrimaryKeySelective(ProductInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_product_info
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    @Update({
        "update b_product_info",
        "set product_name = #{productName,jdbcType=VARCHAR},",
          "rate = #{rate,jdbcType=DECIMAL},",
          "cycle = #{cycle,jdbcType=INTEGER},",
          "release_time = #{releaseTime,jdbcType=DATE},",
          "product_type = #{productType,jdbcType=INTEGER},",
          "product_no = #{productNo,jdbcType=VARCHAR},",
          "product_money = #{productMoney,jdbcType=DECIMAL},",
          "left_product_money = #{leftProductMoney,jdbcType=DECIMAL},",
          "bid_min_limit = #{bidMinLimit,jdbcType=DECIMAL},",
          "bid_max_limit = #{bidMaxLimit,jdbcType=DECIMAL},",
          "product_status = #{productStatus,jdbcType=INTEGER},",
          "product_full_time = #{productFullTime,jdbcType=TIMESTAMP},",
          "product_desc = #{productDesc,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ProductInfo record);
}