#????
spring:
  application:
    name: micr-dataservice
  datasource:
    url: jdbc:mysql://localhost:3306/ylb20230707?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

#mybatis
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

#dubbo配置
dubbo:
  registry:
    address: zookeeper://localhost:2181
  scan:
    base-packages: com.rxee.dataservice.service
  provider:
    timeout: 50000
    retries: 0
