package com.rxee.api.entity;

import java.io.Serializable;
import java.math.BigDecimal;

public class FinanceAccount implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_finance_account.id
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_finance_account.uid
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_finance_account.available_money
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    private BigDecimal availableMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table u_finance_account
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_finance_account.id
     *
     * @return the value of u_finance_account.id
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_finance_account
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    public FinanceAccount withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_finance_account.id
     *
     * @param id the value for u_finance_account.id
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_finance_account.uid
     *
     * @return the value of u_finance_account.uid
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_finance_account
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    public FinanceAccount withUid(Integer uid) {
        this.setUid(uid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_finance_account.uid
     *
     * @param uid the value for u_finance_account.uid
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_finance_account.available_money
     *
     * @return the value of u_finance_account.available_money
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    public BigDecimal getAvailableMoney() {
        return availableMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_finance_account
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    public FinanceAccount withAvailableMoney(BigDecimal availableMoney) {
        this.setAvailableMoney(availableMoney);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_finance_account.available_money
     *
     * @param availableMoney the value for u_finance_account.available_money
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    public void setAvailableMoney(BigDecimal availableMoney) {
        this.availableMoney = availableMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_finance_account
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", uid=").append(uid);
        sb.append(", availableMoney=").append(availableMoney);
        sb.append("]");
        return sb.toString();
    }
}