package com.rxee.api.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class ProductInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product_info.id
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product_info.product_name
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product_info.rate
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    private BigDecimal rate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product_info.cycle
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    private Integer cycle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product_info.release_time
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    private Date releaseTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product_info.product_type
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    private Integer productType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product_info.product_no
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    private String productNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product_info.product_money
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    private BigDecimal productMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product_info.left_product_money
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    private BigDecimal leftProductMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product_info.bid_min_limit
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    private BigDecimal bidMinLimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product_info.bid_max_limit
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    private BigDecimal bidMaxLimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product_info.product_status
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    private Integer productStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product_info.product_full_time
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    private Date productFullTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product_info.product_desc
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    private String productDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table b_product_info
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_product_info.id
     *
     * @return the value of b_product_info.id
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_product_info
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    public ProductInfo withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product_info.id
     *
     * @param id the value for b_product_info.id
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_product_info.product_name
     *
     * @return the value of b_product_info.product_name
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_product_info
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    public ProductInfo withProductName(String productName) {
        this.setProductName(productName);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product_info.product_name
     *
     * @param productName the value for b_product_info.product_name
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_product_info.rate
     *
     * @return the value of b_product_info.rate
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    public BigDecimal getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_product_info
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    public ProductInfo withRate(BigDecimal rate) {
        this.setRate(rate);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product_info.rate
     *
     * @param rate the value for b_product_info.rate
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    public void setRate(BigDecimal rate) {
        this.rate = rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_product_info.cycle
     *
     * @return the value of b_product_info.cycle
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    public Integer getCycle() {
        return cycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_product_info
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    public ProductInfo withCycle(Integer cycle) {
        this.setCycle(cycle);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product_info.cycle
     *
     * @param cycle the value for b_product_info.cycle
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    public void setCycle(Integer cycle) {
        this.cycle = cycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_product_info.release_time
     *
     * @return the value of b_product_info.release_time
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    public Date getReleaseTime() {
        return releaseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_product_info
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    public ProductInfo withReleaseTime(Date releaseTime) {
        this.setReleaseTime(releaseTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product_info.release_time
     *
     * @param releaseTime the value for b_product_info.release_time
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    public void setReleaseTime(Date releaseTime) {
        this.releaseTime = releaseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_product_info.product_type
     *
     * @return the value of b_product_info.product_type
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    public Integer getProductType() {
        return productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_product_info
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    public ProductInfo withProductType(Integer productType) {
        this.setProductType(productType);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product_info.product_type
     *
     * @param productType the value for b_product_info.product_type
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    public void setProductType(Integer productType) {
        this.productType = productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_product_info.product_no
     *
     * @return the value of b_product_info.product_no
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    public String getProductNo() {
        return productNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_product_info
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    public ProductInfo withProductNo(String productNo) {
        this.setProductNo(productNo);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product_info.product_no
     *
     * @param productNo the value for b_product_info.product_no
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    public void setProductNo(String productNo) {
        this.productNo = productNo == null ? null : productNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_product_info.product_money
     *
     * @return the value of b_product_info.product_money
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    public BigDecimal getProductMoney() {
        return productMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_product_info
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    public ProductInfo withProductMoney(BigDecimal productMoney) {
        this.setProductMoney(productMoney);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product_info.product_money
     *
     * @param productMoney the value for b_product_info.product_money
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    public void setProductMoney(BigDecimal productMoney) {
        this.productMoney = productMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_product_info.left_product_money
     *
     * @return the value of b_product_info.left_product_money
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    public BigDecimal getLeftProductMoney() {
        return leftProductMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_product_info
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    public ProductInfo withLeftProductMoney(BigDecimal leftProductMoney) {
        this.setLeftProductMoney(leftProductMoney);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product_info.left_product_money
     *
     * @param leftProductMoney the value for b_product_info.left_product_money
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    public void setLeftProductMoney(BigDecimal leftProductMoney) {
        this.leftProductMoney = leftProductMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_product_info.bid_min_limit
     *
     * @return the value of b_product_info.bid_min_limit
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    public BigDecimal getBidMinLimit() {
        return bidMinLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_product_info
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    public ProductInfo withBidMinLimit(BigDecimal bidMinLimit) {
        this.setBidMinLimit(bidMinLimit);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product_info.bid_min_limit
     *
     * @param bidMinLimit the value for b_product_info.bid_min_limit
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    public void setBidMinLimit(BigDecimal bidMinLimit) {
        this.bidMinLimit = bidMinLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_product_info.bid_max_limit
     *
     * @return the value of b_product_info.bid_max_limit
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    public BigDecimal getBidMaxLimit() {
        return bidMaxLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_product_info
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    public ProductInfo withBidMaxLimit(BigDecimal bidMaxLimit) {
        this.setBidMaxLimit(bidMaxLimit);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product_info.bid_max_limit
     *
     * @param bidMaxLimit the value for b_product_info.bid_max_limit
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    public void setBidMaxLimit(BigDecimal bidMaxLimit) {
        this.bidMaxLimit = bidMaxLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_product_info.product_status
     *
     * @return the value of b_product_info.product_status
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    public Integer getProductStatus() {
        return productStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_product_info
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    public ProductInfo withProductStatus(Integer productStatus) {
        this.setProductStatus(productStatus);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product_info.product_status
     *
     * @param productStatus the value for b_product_info.product_status
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    public void setProductStatus(Integer productStatus) {
        this.productStatus = productStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_product_info.product_full_time
     *
     * @return the value of b_product_info.product_full_time
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    public Date getProductFullTime() {
        return productFullTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_product_info
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    public ProductInfo withProductFullTime(Date productFullTime) {
        this.setProductFullTime(productFullTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product_info.product_full_time
     *
     * @param productFullTime the value for b_product_info.product_full_time
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    public void setProductFullTime(Date productFullTime) {
        this.productFullTime = productFullTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_product_info.product_desc
     *
     * @return the value of b_product_info.product_desc
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    public String getProductDesc() {
        return productDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_product_info
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    public ProductInfo withProductDesc(String productDesc) {
        this.setProductDesc(productDesc);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product_info.product_desc
     *
     * @param productDesc the value for b_product_info.product_desc
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    public void setProductDesc(String productDesc) {
        this.productDesc = productDesc == null ? null : productDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_product_info
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", productName=").append(productName);
        sb.append(", rate=").append(rate);
        sb.append(", cycle=").append(cycle);
        sb.append(", releaseTime=").append(releaseTime);
        sb.append(", productType=").append(productType);
        sb.append(", productNo=").append(productNo);
        sb.append(", productMoney=").append(productMoney);
        sb.append(", leftProductMoney=").append(leftProductMoney);
        sb.append(", bidMinLimit=").append(bidMinLimit);
        sb.append(", bidMaxLimit=").append(bidMaxLimit);
        sb.append(", productStatus=").append(productStatus);
        sb.append(", productFullTime=").append(productFullTime);
        sb.append(", productDesc=").append(productDesc);
        sb.append("]");
        return sb.toString();
    }
}