package com.rxee.api.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class RechargeRecord implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_recharge_record.id
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_recharge_record.uid
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_recharge_record.recharge_no
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    private String rechargeNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_recharge_record.recharge_status
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    private Integer rechargeStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_recharge_record.recharge_money
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    private BigDecimal rechargeMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_recharge_record.recharge_time
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    private Date rechargeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_recharge_record.recharge_desc
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    private String rechargeDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_recharge_record.channel
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    private String channel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table b_recharge_record
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_recharge_record.id
     *
     * @return the value of b_recharge_record.id
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_recharge_record
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    public RechargeRecord withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_recharge_record.id
     *
     * @param id the value for b_recharge_record.id
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_recharge_record.uid
     *
     * @return the value of b_recharge_record.uid
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_recharge_record
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    public RechargeRecord withUid(Integer uid) {
        this.setUid(uid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_recharge_record.uid
     *
     * @param uid the value for b_recharge_record.uid
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_recharge_record.recharge_no
     *
     * @return the value of b_recharge_record.recharge_no
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    public String getRechargeNo() {
        return rechargeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_recharge_record
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    public RechargeRecord withRechargeNo(String rechargeNo) {
        this.setRechargeNo(rechargeNo);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_recharge_record.recharge_no
     *
     * @param rechargeNo the value for b_recharge_record.recharge_no
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    public void setRechargeNo(String rechargeNo) {
        this.rechargeNo = rechargeNo == null ? null : rechargeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_recharge_record.recharge_status
     *
     * @return the value of b_recharge_record.recharge_status
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    public Integer getRechargeStatus() {
        return rechargeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_recharge_record
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    public RechargeRecord withRechargeStatus(Integer rechargeStatus) {
        this.setRechargeStatus(rechargeStatus);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_recharge_record.recharge_status
     *
     * @param rechargeStatus the value for b_recharge_record.recharge_status
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    public void setRechargeStatus(Integer rechargeStatus) {
        this.rechargeStatus = rechargeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_recharge_record.recharge_money
     *
     * @return the value of b_recharge_record.recharge_money
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    public BigDecimal getRechargeMoney() {
        return rechargeMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_recharge_record
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    public RechargeRecord withRechargeMoney(BigDecimal rechargeMoney) {
        this.setRechargeMoney(rechargeMoney);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_recharge_record.recharge_money
     *
     * @param rechargeMoney the value for b_recharge_record.recharge_money
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    public void setRechargeMoney(BigDecimal rechargeMoney) {
        this.rechargeMoney = rechargeMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_recharge_record.recharge_time
     *
     * @return the value of b_recharge_record.recharge_time
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    public Date getRechargeTime() {
        return rechargeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_recharge_record
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    public RechargeRecord withRechargeTime(Date rechargeTime) {
        this.setRechargeTime(rechargeTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_recharge_record.recharge_time
     *
     * @param rechargeTime the value for b_recharge_record.recharge_time
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    public void setRechargeTime(Date rechargeTime) {
        this.rechargeTime = rechargeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_recharge_record.recharge_desc
     *
     * @return the value of b_recharge_record.recharge_desc
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    public String getRechargeDesc() {
        return rechargeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_recharge_record
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    public RechargeRecord withRechargeDesc(String rechargeDesc) {
        this.setRechargeDesc(rechargeDesc);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_recharge_record.recharge_desc
     *
     * @param rechargeDesc the value for b_recharge_record.recharge_desc
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    public void setRechargeDesc(String rechargeDesc) {
        this.rechargeDesc = rechargeDesc == null ? null : rechargeDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_recharge_record.channel
     *
     * @return the value of b_recharge_record.channel
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    public String getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_recharge_record
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    public RechargeRecord withChannel(String channel) {
        this.setChannel(channel);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_recharge_record.channel
     *
     * @param channel the value for b_recharge_record.channel
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    public void setChannel(String channel) {
        this.channel = channel == null ? null : channel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_recharge_record
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", uid=").append(uid);
        sb.append(", rechargeNo=").append(rechargeNo);
        sb.append(", rechargeStatus=").append(rechargeStatus);
        sb.append(", rechargeMoney=").append(rechargeMoney);
        sb.append(", rechargeTime=").append(rechargeTime);
        sb.append(", rechargeDesc=").append(rechargeDesc);
        sb.append(", channel=").append(channel);
        sb.append("]");
        return sb.toString();
    }
}