package com.rxee.dataservice.mapper;

import com.rxee.entity.IncomeRecord;
import org.apache.ibatis.annotations.*;

public interface IncomeRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_income_record
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    @Delete({
        "delete from b_income_record",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_income_record
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    @Insert({
        "insert into b_income_record (id, uid, ",
        "prod_id, bid_id, bid_money, ",
        "income_date, income_money, ",
        "income_status)",
        "values (#{id,jdbcType=INTEGER}, #{uid,jdbcType=INTEGER}, ",
        "#{prodId,jdbcType=INTEGER}, #{bidId,jdbcType=INTEGER}, #{bidMoney,jdbcType=DECIMAL}, ",
        "#{incomeDate,jdbcType=TIMESTAMP}, #{incomeMoney,jdbcType=DECIMAL}, ",
        "#{incomeStatus,jdbcType=INTEGER})"
    })
    int insert(IncomeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_income_record
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    int insertSelective(IncomeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_income_record
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    @Select({
        "select",
        "id, uid, prod_id, bid_id, bid_money, income_date, income_money, income_status",
        "from b_income_record",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.rxee.backend.mapper.IncomeRecordMapper.BaseResultMap")
    IncomeRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_income_record
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    int updateByPrimaryKeySelective(IncomeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_income_record
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    @Update({
        "update b_income_record",
        "set uid = #{uid,jdbcType=INTEGER},",
          "prod_id = #{prodId,jdbcType=INTEGER},",
          "bid_id = #{bidId,jdbcType=INTEGER},",
          "bid_money = #{bidMoney,jdbcType=DECIMAL},",
          "income_date = #{incomeDate,jdbcType=TIMESTAMP},",
          "income_money = #{incomeMoney,jdbcType=DECIMAL},",
          "income_status = #{incomeStatus,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(IncomeRecord record);
}