package com.rxee.dataservice.mapper;

import com.rxee.entity.RechargeRecord;
import org.apache.ibatis.annotations.*;

public interface RechargeRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_recharge_record
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    @Delete({
        "delete from b_recharge_record",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_recharge_record
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    @Insert({
        "insert into b_recharge_record (id, uid, ",
        "recharge_no, recharge_status, ",
        "recharge_money, recharge_time, ",
        "recharge_desc, channel)",
        "values (#{id,jdbcType=INTEGER}, #{uid,jdbcType=INTEGER}, ",
        "#{rechargeNo,jdbcType=VARCHAR}, #{rechargeStatus,jdbcType=INTEGER}, ",
        "#{rechargeMoney,jdbcType=DECIMAL}, #{rechargeTime,jdbcType=TIMESTAMP}, ",
        "#{rechargeDesc,jdbcType=VARCHAR}, #{channel,jdbcType=VARCHAR})"
    })
    int insert(RechargeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_recharge_record
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    int insertSelective(RechargeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_recharge_record
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    @Select({
        "select",
        "id, uid, recharge_no, recharge_status, recharge_money, recharge_time, recharge_desc, ",
        "channel",
        "from b_recharge_record",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.rxee.backend.mapper.RechargeRecordMapper.BaseResultMap")
    RechargeRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_recharge_record
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    int updateByPrimaryKeySelective(RechargeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_recharge_record
     *
     * @mbg.generated Sat Jul 08 01:57:23 CST 2023
     */
    @Update({
        "update b_recharge_record",
        "set uid = #{uid,jdbcType=INTEGER},",
          "recharge_no = #{rechargeNo,jdbcType=VARCHAR},",
          "recharge_status = #{rechargeStatus,jdbcType=INTEGER},",
          "recharge_money = #{rechargeMoney,jdbcType=DECIMAL},",
          "recharge_time = #{rechargeTime,jdbcType=TIMESTAMP},",
          "recharge_desc = #{rechargeDesc,jdbcType=VARCHAR},",
          "channel = #{channel,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(RechargeRecord record);
}