spring:
  application:
    name: micr-web
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

#???
server:
  port: 8000
  servlet:
    context-path: /api
    encoding:
      enabled: true
      charset: UTF-8
      force: true

#dubbo??
dubbo:
  registry:
    address: zookeeper://localhost:2181
  scan:
    base-packages: com.rxee.front

  consumer:
    check: false
    timeout: 50000
    retries: 0
